### ISSUE TITLE
Content is not allowed in prolog

### ISSUE THREAD

**Issue by brianwarehime** [SneakersInc/HoneyMalt#1]
Would love to start experimenting with this, however, ran into an issue when trying to get it up and running. 

I added the honeypot to Maltego, modified it to point to my kippo IP, ran the machine, and then I get these errors during each iteration:

ParseError at [row,col]:[1,1]
Message: Content is not allowed in prolog.
Transform HoneyMalt: Kippo IPs returned with an error: ParseError at [row,col]:[1,1]
Message: Content is not allowed in prolog.
Transform HoneyMalt: Kippo IPs done
Running transform HoneyMalt: Kippo IPs on 1 entities.

It's on iteration 19 right now, and nothing is happening. I'm running Maltego Tungsten CE 3.4.1 on Mac OS X Mavericks 10.9.4. Kippo honeypot is on a Debian 7.4.0 box. 

Any suggestions?

**Comment by catalyst256** [comment]
Hi Brian,

Sorry HoneyMalt isn't working as expected, lets see if we can fix that. The error you are getting is Maltego's way of saying that you are getting some text back in the transform rather than the entity it's expecting. I'm going to throw a series of questions your way to see if we can track down the problem, apologises if they seem a bit random and no offence is meant.
1. Are you using Kippo with MySQL logging?
2. If you are using Kippo with MySQL logging is it using the standard port?
3. Did you update the HoneyMalt.conf file (should in the src directory) with your specific Kippo DB details?
4. MySQL by default doesn't allow remote SQL queries, I needed to run the following command within MySQL to get it to work.

GRANT ALL ON kippo.\* TO kippo@'IPADDR' IDENTIFIED BY 'Kippo-DB-Pass';

You need to change the IPADDR and Kippo-DB-Pass to match your setup

If none of these solve the issue I will talk you through enabling debugging on the transform and I will add some error catching and push it up to the repo later today.

Thanks again for trying HoneyMalt and sorry you are having issues.

Adam

**Comment by brianwarehime** [comment]
Adam,

Thanks for the response. So, I'll post what I have to make sure I have it all right:
1. Are you using Kippo with MySQL logging?

kippo.cfg
[database_mysql]
host = localhost
database = kippo
username = kippo
password = Kippo-DB-pass
port = 3306
1. If you are using Kippo with MySQL logging is it using the standard port?

See above, port = 3306
1. Did you update the HoneyMalt.conf file (should in the src directory) with your specific Kippo DB details?

→ cat HoneyMalt.conf
[kippodb]
database = 'kippo'
username = 'kippo'
password = 'Kippo-DB-pass'
1. MySQL by default doesn't allow remote SQL queries, I needed to run the following command within MySQL to get it to work.

root@kippo:~# mysql --user=root -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 37
Server version: 5.5.38-0+wheezy1 (Debian)

Copyright (c) 2000, 2014, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> GRANT ALL ON kippo.\* TO kippo@'192.168.1.2' IDENTIFIED BY 'Kippo-DB-Pass';
Query OK, 0 rows affected (0.02 sec)

mysql> exit

It also might be worth noting that I am using Kippo-graph with no issues. 

Kippo-graph config.php
define('DB_HOST', 'localhost');
define('DB_USER', 'kippo');
define('DB_PASS', 'Kippo-DB-pass');
define('DB_NAME', 'kippo');
define('DB_PORT', '3306');

Does it look like I am missing anything, or messed something up? If you have time and if it would be easier to troubleshoot, we could do a teamviewer session if you'd like.

Thanks again for the response,

Brian

**Comment by catalyst256** [comment]
Hi Brian,

If you do a git pull on from the HoneyMalt directory I've added some exception handling for the first transform. I have a feeling it's having issues connecting to the database from your Maltego machine. The error should be captured and returned in the Transform Output window. If you can try and then send me that error???

Thanks,

Adam

**Comment by brianwarehime** [comment]
Adam,

Figured out what it was, I had bind-address still set to 127.0.0.1 in the mysql configuration. After that change it was able to connect, however, I got a password error, and realized I had a lowercase where it shouldn't be.

It's running now and looking awesome! Sorry for the trouble, and thanks for the help. The extra debugging definitely helped out.

Thanks again!

**Comment by catalyst256** [comment]
Brian, that's awesome glad we managed to get it sorted. I'm just going through and adding the exception handling to the other transforms now.

Please let me know if you have other issues or feedback.

Adam
